<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_dynamic_add_to_cart</name>
   <tag></tag>
   <elementGuidId>c2120e31-1c34-405a-b7f2-d0e25f9f8120</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//div[text()='${productName}']/ancestor::div[@class='inventory_item_description']//button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[text()='${productName}']/ancestor::div[@class='inventory_item_description']//button</value>
      <webElementGuid>c30de124-14bd-49f3-aa4f-20948a75977f</webElementGuid>
   </webElementProperties>
</WebElementEntity>
