<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lbl_overview_tax</name>
   <tag></tag>
   <elementGuidId>6fad5088-b0ef-404e-bd12-32f6eac508ae</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@data-test='tax-label']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@data-test='tax-label']</value>
      <webElementGuid>50ec7b33-4c99-4e49-a1c6-3444cdbab99a</webElementGuid>
   </webElementProperties>
</WebElementEntity>
